config-version: 1
properties:
  chat-prefix: '&7[&dCSF&7] '
  
  #Database to use, sqlite or mysql. 
  db-type: sqlite
  
  #Default permission access. If you don't want ops access set to false.
  permission-default: op
  
  # Check for new version on startup.
  check-new-version: true
  
  # Help the developer know how popular the plugin is.
  use-metrics: true
  
  # When possible, run db queries in seperate thread to reduce lag.
  async-db-queries: true
  
  # Show debug messages.
  debug-messages: false
  
  # Auto add shop upon creation to our database.
  auto-register: true
  
  #Decimal places to round prices.
  price-rounding: 2
  
  # When a chunk is loaded for the first time, check if we have any known shops in the chunk and check the chunk if they're still there. Delete if not.
  verify-chunk-shops: true
  
  # Number of shops to display in the search/buy/sell commands.
  search-results: 10
  
  # If a shop owner has multiple shops for the same item, show only one.
  one-owner-per-results: true
  
  # Name of your admin shop, to bypass our supply/balance check.
  admin-shop: "Admin Shop"
  
# MySQL DB info.
mysql:
  hostname: localhost
  username: root
  password: CHANGEME
  port: 3306
  database: minecraft
  prefix: CSF_
  
  # Your iConomy db table, to confirm a shop can afford to an item. Set to false if you don't want to use iConomy with MySQL.
  iConomy_table: iConomy