name: ChestShopFinder
main: com.cyprias.ChestShopFinder.Plugin
authors: [Cyprias, ABCRic]
description: Find ChestShops.
version: 0.9.6

commands:
  csf:
    description: Get available commands